name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew clean test --continue
      continue-on-error: true

    - name: Print test results to logs
      run: |
          echo "==== JUnit Test Results ===="
          if [ -d "build/test-results/test" ]; then
            find build/test-results/test -name "*.xml" -exec cat {} +
          else
            echo "No test results found."
          fi
