name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew clean test --continue
      continue-on-error: true  # Ensures that the build doesn't fail even if tests fail

    - name: Upload JUnit test results
      if: always()  # Ensures this step runs even if tests fail
      uses: actions/upload-artifact@v2
      with:
        name: junit-test-results
        path: build/test-results/test/*.xml
